pull_request_rules:
- name: metworkbot automerge
  actions:
    label:
      add:
        - Merge Now
  conditions:
    - author=metworkbot
    - -merged
    - -closed
{% if cookiecutter.integration_level|int >= 4 %}
- name: integration branch
  actions:
    label:
      add:
        - Merge Now
  conditions:
    - base=integration
    - -merged
    - -closed
    - label!=no-mergify
    - '#approved-reviews-by>=1'
    - status-success=license/cla
    - author!=metworkbot
{% if cookiecutter.repo != 'mfext' and cookiecutter.repo != 'testrepo' %}
    - status-success=continuous-integration/drone/pr
{% endif %}
{% endif %}
- name: merge action
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: false
    delete_head_branch: {}
    label:
      remove:
        - Merge Now
  conditions:
    - label!=no-mergify
    - label=Merge Now
