pull_request_rules:
- name: metworkbot automerge
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: false
  conditions:
    - author=metworkbot
{% if cookiecutter.integration_level|int >= 4 %}
- name: integration branch
  actions:
    merge:
      method: rebase
      rebase_fallback: merge
      strict: true
    delete_head_branch: {}
  conditions:
    - base=integration
    - label!=no-mergify
    - '#approved-reviews-by>=1'
    - status-success=license/cla
    - author!=metworkbot
{% if cookiecutter.repo != "mfext" %}
    - status-success=continuous-integration/drone/pr
{% endif %}
{% endif %}
